<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZIAdAHq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZIAdAHq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZIAdAHq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZIAdAHq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZIAdAHq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZIAdAHq',
    'container.build_id' => '39840894',
    'container.build_time' => 1650739112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZIAdAHq');
